### ISSUE TITLE
Inlined GIFs don't autoplay in teams

### ISSUE THREAD

**Issue by alancast** [alancast/GifBot#7]
Because of this we have disabled inline GIFs in GifBot. If teams allows inlining to work just uncomment the lines after TODO:#7 and this will work

**Comment by remyjette** [comment]
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-conversations

> "Animated GIF not officially supported"

There's also the "AnimationCard", but Media cards (included animation cards) are also listed as Not Supported.: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-cards

Uservoice idea for richer card support is here: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/31999282-richer-cards-and-messages

Probably can just close this for now, doesn't seem like it's coming any time soon
